"""
Brand Kit — PDF and ZIP packaging.
"""
import io
import json
import zipfile
import logging
from fpdf import FPDF

logger = logging.getLogger("creatorstudio.brand_kit")


def sanitize(text):
    if not text:
        return ""
    return str(text).encode('latin-1', 'replace').decode('latin-1')


def generate_brand_kit_pdf(job: dict) -> bytes:
    """Generate a premium brand kit PDF from job artifacts."""
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)

    brief = job.get("brief", {})
    biz = brief.get("business_name", "Brand Kit")
    artifacts = job.get("artifacts", {})

    # ── COVER PAGE ──
    pdf.add_page()
    pdf.set_fill_color(8, 8, 24)
    pdf.rect(0, 0, 210, 297, "F")
    pdf.set_draw_color(60, 60, 120)
    pdf.set_line_width(1.5)
    pdf.rect(10, 10, 190, 277)

    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_xy(15, 60)
    pdf.cell(180, 18, sanitize(biz), align="C")

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(160, 160, 210)
    pdf.set_xy(15, 85)
    pdf.cell(180, 10, "Brand Kit", align="C")

    mode_label = job.get("mode", "pro").title()
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(120, 120, 160)
    pdf.set_xy(15, 100)
    pdf.cell(180, 8, f"{mode_label} Edition | Generated by Visionary Suite", align="C")

    if brief.get("industry"):
        pdf.set_xy(15, 115)
        pdf.cell(180, 8, f"Industry: {sanitize(brief['industry'])}", align="C")

    # ── BRAND STORY ──
    for key in ("short_brand_story", "long_brand_story"):
        art = artifacts.get(key, {})
        if art.get("status") in ("READY", "FALLBACK_READY") and art.get("data"):
            pdf.add_page()
            pdf.set_fill_color(8, 8, 24)
            pdf.rect(0, 0, 210, 297, "F")

            title = "Short Brand Story" if key == "short_brand_story" else "Full Brand Story"
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Helvetica", "B", 22)
            pdf.set_xy(15, 20)
            pdf.cell(180, 12, title, align="L")
            pdf.set_draw_color(80, 80, 140)
            pdf.line(15, 35, 195, 35)

            story = art["data"].get(key, "")
            pdf.set_text_color(200, 200, 230)
            pdf.set_font("Helvetica", "", 12)
            pdf.set_xy(15, 42)
            pdf.multi_cell(180, 7, sanitize(story))

    # ── MISSION / VISION / VALUES ──
    mvv = artifacts.get("mission_vision_values", {})
    if mvv.get("status") in ("READY", "FALLBACK_READY") and mvv.get("data"):
        pdf.add_page()
        pdf.set_fill_color(8, 8, 24)
        pdf.rect(0, 0, 210, 297, "F")

        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_xy(15, 20)
        pdf.cell(180, 12, "Mission, Vision & Values", align="L")
        pdf.line(15, 35, 195, 35)

        d = mvv["data"]
        y = 42
        for label, field in [("Mission", "mission"), ("Vision", "vision")]:
            pdf.set_text_color(100, 180, 255)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_xy(15, y)
            pdf.cell(180, 8, label)
            y += 10
            pdf.set_text_color(200, 200, 230)
            pdf.set_font("Helvetica", "", 11)
            pdf.set_xy(15, y)
            pdf.multi_cell(180, 6, sanitize(d.get(field, "")))
            y = pdf.get_y() + 8

        if d.get("values"):
            pdf.set_text_color(100, 180, 255)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_xy(15, y)
            pdf.cell(180, 8, "Core Values")
            y += 10
            pdf.set_text_color(200, 200, 230)
            pdf.set_font("Helvetica", "", 11)
            for v in d["values"]:
                pdf.set_xy(20, y)
                pdf.cell(170, 6, sanitize(f"  {v}"))
                y += 7

    # ── TAGLINES ──
    taglines = artifacts.get("taglines", {})
    if taglines.get("status") in ("READY", "FALLBACK_READY") and taglines.get("data"):
        pdf.add_page()
        pdf.set_fill_color(8, 8, 24)
        pdf.rect(0, 0, 210, 297, "F")

        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_xy(15, 20)
        pdf.cell(180, 12, "Tagline Options", align="L")
        pdf.line(15, 35, 195, 35)

        y = 42
        for t in taglines["data"].get("taglines", []):
            text = t if isinstance(t, str) else t.get("text", "")
            style = "" if isinstance(t, str) else t.get("style", "")
            pdf.set_text_color(230, 230, 250)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_xy(20, y)
            pdf.cell(140, 7, sanitize(f'"{text}"'))
            if style:
                pdf.set_text_color(120, 120, 160)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_xy(160, y)
                pdf.cell(35, 7, sanitize(style), align="R")
            y += 10

    # ── COLOR PALETTES ──
    palettes = artifacts.get("color_palettes", {})
    if palettes.get("status") in ("READY", "FALLBACK_READY") and palettes.get("data"):
        pdf.add_page()
        pdf.set_fill_color(8, 8, 24)
        pdf.rect(0, 0, 210, 297, "F")

        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_xy(15, 20)
        pdf.cell(180, 12, "Color Palettes", align="L")
        pdf.line(15, 35, 195, 35)

        y = 42
        for p in palettes["data"].get("palettes", []):
            pdf.set_text_color(200, 200, 230)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_xy(15, y)
            pdf.cell(180, 7, sanitize(p.get("name", "")))
            y += 10

            # Draw color swatches
            colors = [("Primary", p.get("primary")), ("Secondary", p.get("secondary")),
                      ("Accent", p.get("accent")), ("Background", p.get("background"))]
            x = 15
            for label, hex_color in colors:
                if hex_color:
                    try:
                        r = int(hex_color[1:3], 16)
                        g = int(hex_color[3:5], 16)
                        b = int(hex_color[5:7], 16)
                        pdf.set_fill_color(r, g, b)
                        pdf.rect(x, y, 30, 15, "F")
                        pdf.set_text_color(180, 180, 200)
                        pdf.set_font("Helvetica", "", 7)
                        pdf.set_xy(x, y + 16)
                        pdf.cell(30, 5, sanitize(f"{label}\n{hex_color}"), align="C")
                    except (ValueError, IndexError):
                        pass
                x += 42
            y += 28

            pdf.set_text_color(140, 140, 170)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_xy(15, y)
            pdf.cell(180, 5, sanitize(p.get("meaning", "")))
            y += 14

    # ── BACK COVER ──
    pdf.add_page()
    pdf.set_fill_color(8, 8, 24)
    pdf.rect(0, 0, 210, 297, "F")
    pdf.set_text_color(80, 80, 120)
    pdf.set_font("Helvetica", "I", 14)
    pdf.set_xy(15, 120)
    pdf.cell(180, 10, sanitize(f"{biz} Brand Kit"), align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(15, 140)
    pdf.cell(180, 8, "Created with Visionary Suite", align="C")

    return bytes(pdf.output())


def generate_brand_kit_zip(job: dict) -> bytes:
    """Generate a ZIP bundle with PDF, TXT, and JSON exports."""
    brief = job.get("brief", {})
    biz = brief.get("business_name", "brand")
    artifacts = job.get("artifacts", {})

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # PDF
        try:
            pdf_bytes = generate_brand_kit_pdf(job)
            zf.writestr(f"{biz}_brand_kit.pdf", pdf_bytes)
        except Exception as e:
            logger.warning(f"PDF generation failed in ZIP: {e}")

        # TXT export
        txt_parts = [f"=== {biz} BRAND KIT ===\n"]
        for art_type, art in artifacts.items():
            if art.get("status") in ("READY", "FALLBACK_READY") and art.get("data"):
                txt_parts.append(f"\n--- {art_type.upper().replace('_', ' ')} ---\n")
                data = art["data"]
                if isinstance(data, dict):
                    for k, v in data.items():
                        if isinstance(v, list):
                            txt_parts.append(f"\n{k}:")
                            for item in v:
                                if isinstance(item, dict):
                                    txt_parts.append(f"  - {json.dumps(item)}")
                                else:
                                    txt_parts.append(f"  - {item}")
                        else:
                            txt_parts.append(f"\n{k}:\n{v}")
        zf.writestr(f"{biz}_brand_kit.txt", "\n".join(txt_parts))

        # JSON export
        json_data = {
            "business_name": biz,
            "mode": job.get("mode"),
            "brief": brief,
            "outputs": {},
        }
        for art_type, art in artifacts.items():
            if art.get("status") in ("READY", "FALLBACK_READY") and art.get("data"):
                json_data["outputs"][art_type] = art["data"]
        zf.writestr(f"{biz}_brand_kit.json", json.dumps(json_data, indent=2))

    return buf.getvalue()
