import React, { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components/ui/button';
import {
  ArrowLeft, Download, RefreshCw, Instagram, Youtube, Facebook,
  CheckCircle, Clock, AlertCircle, Film, Share2, Sparkles
} from 'lucide-react';

const API_URL = process.env.REACT_APP_BACKEND_URL;

const platformConfig = {
  Instagram: { color: 'from-pink-500 to-orange-500', icon: Instagram, bg: 'bg-pink-500/20', text: 'text-pink-400' },
  YouTube: { color: 'from-red-500 to-red-700', icon: Youtube, bg: 'bg-red-500/20', text: 'text-red-400' },
  Facebook: { color: 'from-blue-500 to-blue-700', icon: Facebook, bg: 'bg-blue-500/20', text: 'text-blue-400' },
};

function StatusBadge({ status }) {
  if (status === 'COMPLETED') return <span className="flex items-center gap-1 text-green-400 text-sm font-medium"><CheckCircle className="w-4 h-4" /> Ready</span>;
  if (status === 'GENERATING') return <span className="flex items-center gap-1 text-amber-400 text-sm font-medium animate-pulse"><Clock className="w-4 h-4 animate-spin" /> Generating...</span>;
  if (status === 'FAILED') return <span className="flex items-center gap-1 text-red-400 text-sm font-medium"><AlertCircle className="w-4 h-4" /> Failed</span>;
  if (status === 'PENDING') return <span className="flex items-center gap-1 text-slate-400 text-sm font-medium"><Clock className="w-4 h-4" /> Queued</span>;
  if (status === 'FILE_MISSING') return <span className="flex items-center gap-1 text-amber-400 text-sm font-medium"><AlertCircle className="w-4 h-4" /> Needs Redeploy</span>;
  return <span className="flex items-center gap-1 text-slate-500 text-sm"><Clock className="w-4 h-4" /> Not Generated</span>;
}

export default function PromoVideos() {
  const [videos, setVideos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchStatus = useCallback(async (isRefresh = false) => {
    try {
      if (isRefresh) setRefreshing(true);
      const res = await fetch(`${API_URL}/api/promo-videos/status`);
      if (res.ok) {
        const data = await res.json();
        setVideos(data.videos || []);
      }
    } catch (e) {
      console.error('Failed to fetch video status:', e);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchStatus();
    const interval = setInterval(() => fetchStatus(), 15000);
    return () => clearInterval(interval);
  }, [fetchStatus]);

  const hasGenerating = videos.some(v => v.status === 'GENERATING' || v.status === 'PENDING');
  const completedCount = videos.filter(v => v.status === 'COMPLETED').length;

  const handleDownload = (video) => {
    const link = document.createElement('a');
    link.href = `${API_URL}${video.downloadUrl}`;
    link.download = video.filename;
    link.target = '_blank';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-slate-950 text-white">
      <header className="bg-slate-900/80 backdrop-blur-sm border-b border-slate-700/50">
        <div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link to="/app">
              <Button variant="ghost" size="sm" className="text-slate-300 hover:text-white hover:bg-white/10">
                <ArrowLeft className="w-4 h-4 mr-2" /> Dashboard
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Film className="w-6 h-6 text-purple-400" />
              <span className="text-xl font-bold">Promo Videos</span>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => fetchStatus(true)}
            disabled={refreshing}
            className="border-slate-600 text-slate-300 hover:text-white"
            data-testid="refresh-status-btn"
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} /> Refresh
          </Button>
        </div>
      </header>

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Hero */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-500/20 border border-purple-500/30 rounded-full mb-4">
            <Sparkles className="w-4 h-4 text-purple-400" />
            <span className="text-purple-300 text-sm font-medium">AI-Generated with Sora 2</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold mb-3">Your Promotional Videos</h1>
          <p className="text-slate-400 max-w-2xl mx-auto">
            {hasGenerating
              ? 'Your videos are being generated by Sora 2 AI. This typically takes 3-5 minutes per video. The page auto-refreshes every 15 seconds.'
              : `${completedCount} of ${videos.length} videos ready for download. Share them across all your social platforms!`}
          </p>
        </div>

        {/* Progress Bar */}
        {hasGenerating && (
          <div className="mb-8 bg-slate-800/50 rounded-xl border border-slate-700/50 p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm text-slate-400">Generation Progress</span>
              <span className="text-sm text-purple-400 font-medium">{completedCount}/{videos.length} complete</span>
            </div>
            <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-purple-500 to-indigo-500 rounded-full transition-all duration-500"
                style={{ width: `${(completedCount / Math.max(videos.length, 1)) * 100}%` }}
              />
            </div>
          </div>
        )}

        {/* Video Cards */}
        {loading ? (
          <div className="flex justify-center py-20">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-500" />
          </div>
        ) : (
          <div className="grid md:grid-cols-2 gap-6">
            {videos.map((video) => {
              const config = platformConfig[video.platform] || platformConfig.Instagram;
              const PlatformIcon = config.icon;
              return (
                <div
                  key={video.id}
                  className="bg-slate-800/50 rounded-2xl border border-slate-700/50 overflow-hidden hover:border-slate-600/50 transition-all"
                  data-testid={`video-card-${video.id}`}
                >
                  {/* Video Preview or Placeholder */}
                  <div className="aspect-video bg-slate-900 relative flex items-center justify-center">
                    {video.status === 'COMPLETED' && video.downloadUrl ? (
                      <video
                        src={`${API_URL}${video.downloadUrl}`}
                        controls
                        className="w-full h-full object-contain"
                        preload="metadata"
                        data-testid={`video-player-${video.id}`}
                      />
                    ) : (
                      <div className="text-center">
                        <div className={`w-16 h-16 rounded-full ${config.bg} flex items-center justify-center mx-auto mb-3`}>
                          {video.status === 'GENERATING' ? (
                            <RefreshCw className={`w-8 h-8 ${config.text} animate-spin`} />
                          ) : (
                            <PlatformIcon className={`w-8 h-8 ${config.text}`} />
                          )}
                        </div>
                        <StatusBadge status={video.status} />
                        {video.error && <p className="text-red-400/70 text-xs mt-2 px-4">{video.error.substring(0, 80)}</p>}
                      </div>
                    )}
                    {/* Platform badge */}
                    <div className={`absolute top-3 left-3 px-3 py-1 rounded-full bg-gradient-to-r ${config.color} text-white text-xs font-bold flex items-center gap-1`}>
                      <PlatformIcon className="w-3 h-3" /> {video.platform}
                    </div>
                  </div>

                  {/* Info */}
                  <div className="p-5">
                    <div className="flex items-center justify-between mb-2">
                      <h3 className="font-bold text-white text-lg">{video.label}</h3>
                      <StatusBadge status={video.status} />
                    </div>
                    <div className="flex items-center gap-3 text-sm text-slate-400 mb-4">
                      <span>{video.format}</span>
                      <span className="text-slate-600">|</span>
                      <span>{video.duration}</span>
                      {video.fileSizeMB > 0 && (
                        <>
                          <span className="text-slate-600">|</span>
                          <span>{video.fileSizeMB} MB</span>
                        </>
                      )}
                    </div>

                    {video.status === 'COMPLETED' && video.downloadUrl ? (
                      <div className="flex gap-3">
                        <Button
                          onClick={() => handleDownload(video)}
                          className="flex-1 bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-600 hover:to-indigo-600"
                          data-testid={`download-${video.id}`}
                        >
                          <Download className="w-4 h-4 mr-2" /> Download MP4
                        </Button>
                        <Button
                          variant="outline"
                          onClick={() => window.open(`${API_URL}${video.downloadUrl}`, '_blank')}
                          className="border-slate-600 text-slate-300 hover:text-white"
                          data-testid={`preview-${video.id}`}
                        >
                          <Share2 className="w-4 h-4" />
                        </Button>
                      </div>
                    ) : video.status === 'COMPLETED' && !video.downloadUrl ? (
                      <div className="h-10 flex items-center justify-center text-amber-400 text-sm">
                        Video generated but file not found. Please redeploy or regenerate.
                      </div>
                    ) : (
                      <div className="h-10 flex items-center justify-center text-slate-500 text-sm">
                        {video.status === 'GENERATING' ? 'Generating with Sora 2... (3-5 min)' : video.status === 'FAILED' ? 'Generation failed' : 'Waiting in queue...'}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Tips Section */}
        <div className="mt-10 bg-slate-800/30 rounded-2xl border border-slate-700/30 p-6">
          <h3 className="text-lg font-bold text-white mb-3">Posting Tips</h3>
          <div className="grid sm:grid-cols-2 gap-4 text-sm text-slate-400">
            <div>
              <p className="text-white font-medium mb-1">Instagram Reel & Story</p>
              <p>Upload directly to Instagram. Add trending audio, hashtags like #AITools #ContentCreation #ViralContent for maximum reach.</p>
            </div>
            <div>
              <p className="text-white font-medium mb-1">YouTube Shorts</p>
              <p>Upload as a Short. Add title: "This AI Tool Creates Viral Content in 60 Seconds" with relevant tags.</p>
            </div>
            <div>
              <p className="text-white font-medium mb-1">Facebook Reel</p>
              <p>Share as a Reel on your page. Pin it and boost it for wider reach. Cross-post to groups.</p>
            </div>
            <div>
              <p className="text-white font-medium mb-1">Best Times to Post</p>
              <p>Tuesday-Thursday, 10AM-1PM or 7PM-9PM local time for maximum engagement.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
